name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts


      - name: Create .env and restart containers
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << ENDSSH
            cd ~/TBODEMY_FINAL_/deployment
            
            # Crear archivo .env
            cat > .env << ENVEOF
          POSTGRES_USER=${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          OPEN_API_KEY=${{ secrets.OPEN_API_KEY }}
          AZURE_SPEECH_KEY=${{ secrets.AZURE_SPEECH_KEY }}
          ENVEOF
            
            # Reiniciar contenedores
            docker compose down
            docker compose up --build -d
            docker compose ps
          ENDSSH


      - name: Deploy to server
        run: |
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude 'venv' \
            --exclude '.venv' \
            --exclude '__pycache__' \
            --exclude '.git' \
            --exclude '.next' \
            -e "ssh -i ~/.ssh/deploy_key" \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/TBODEMY_FINAL_/

